### ISSUE TITLE
Question Two

### ISSUE THREAD

**Issue by mugoh** [NekesaH/AssemblyLab1#1]
### Question description:
![Screenshot from 2020-08-28 14-02-40](https://user-images.githubusercontent.com/44059971/91553283-ce2fd080-e935-11ea-9c6b-f861ce6751c7.png)

### Checkmarks

**TODO** items to be ticked upon completion. Once all are completed, the issue should be closed

- [x] Part One (In Yellow) Assigned to @NekesaH 
- [x] Part Two (In Brown) Assigned to @MabelOlivia 
- [x] Part Three (In Green) Assigned to @Nkatha-Imanene 
- [x] Ensure input is below 100 and and greater that 0

Resolved by #4

**Comment by mugoh** [comment]
Complete. Closing this
